"""Discover, validate, install, and check repository-owned loop packages."""

from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
import re
import tempfile
import tomllib
from typing import Any, Mapping


DEFAULT_LOOP_ID = "three-agent-dev"
MANIFEST_SCHEMA_VERSION = 2
MANAGED_HEADER = "# @generated by codex-crew loop adapter v1\n"
_ID_PATTERN = re.compile(r"^[a-z][a-z0-9-]*$")
_ROLE_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")
_PROFILE_PATTERN = re.compile(r"^[a-z0-9][a-z0-9.-]*$")


class LoopPackageError(ValueError):
    """A loop package or managed runtime installation is invalid."""


@dataclass(frozen=True)
class LoopRole:
    id: str
    instructions_path: Path
    runtime_profile: str
    model: str
    reasoning_effort: str
    service_tier: str


@dataclass(frozen=True)
class EvenHorizontalTmuxLayout:
    name: str
    columns: int
    equal_width: bool


@dataclass(frozen=True)
class TmuxSplitStep:
    role: str
    target: str
    direction: str
    percentage: int


@dataclass(frozen=True)
class SplitPlanTmuxLayout:
    name: str
    steps: tuple[TmuxSplitStep, ...]


TmuxLayout = EvenHorizontalTmuxLayout | SplitPlanTmuxLayout


@dataclass(frozen=True)
class LoopPackage:
    id: str
    root: Path
    manifest_path: Path
    manual_path: Path
    roles: tuple[LoopRole, ...]
    communication_role: str
    layout: TmuxLayout


@dataclass(frozen=True)
class InstalledProfile:
    role: str
    runtime_profile: str
    adapter_path: Path
    symlink_path: Path


def repository_root() -> Path:
    return Path(__file__).resolve().parents[1]


def default_loops_dir() -> Path:
    return repository_root() / "loops"


def default_managed_root() -> Path:
    return repository_root() / ".codex-crew" / "generated"


def resolve_codex_home(value: str | Path | None = None) -> Path:
    configured = value if value is not None else os.environ.get("CODEX_HOME")
    return (
        Path(configured).expanduser().absolute()
        if configured
        else (Path.home() / ".codex").absolute()
    )


def discover_loop_packages(
    loops_dir: str | Path | None = None,
) -> tuple[LoopPackage, ...]:
    root = _loops_root(loops_dir)
    packages: list[LoopPackage] = []
    for child in sorted(root.iterdir(), key=lambda path: path.name):
        if not child.is_dir() or child.name.startswith("."):
            continue
        manifest = child / "manifest.toml"
        if not manifest.is_file():
            raise LoopPackageError(
                f"loop package directory has no manifest.toml: {child}"
            )
        packages.append(_load_manifest(manifest))

    ids = [package.id for package in packages]
    if len(ids) != len(set(ids)):
        raise LoopPackageError("loop package IDs must be unique")

    profiles: dict[str, str] = {}
    for package in packages:
        for role in package.roles:
            owner = profiles.setdefault(role.runtime_profile, package.id)
            if owner != package.id:
                raise LoopPackageError(
                    "runtime profile is shared by multiple loop packages: "
                    f"{role.runtime_profile}"
                )
    return tuple(packages)


def load_loop_package(
    loop_id: str = DEFAULT_LOOP_ID,
    *,
    loops_dir: str | Path | None = None,
) -> LoopPackage:
    if not _ID_PATTERN.fullmatch(loop_id):
        raise LoopPackageError(f"invalid loop ID: {loop_id!r}")
    packages = {package.id: package for package in discover_loop_packages(loops_dir)}
    try:
        return packages[loop_id]
    except KeyError as error:
        available = ", ".join(sorted(packages)) or "none"
        raise LoopPackageError(
            f"unknown loop package {loop_id!r}; available: {available}"
        ) from error


def render_profile_adapter(package: LoopPackage, role: LoopRole) -> str:
    instructions = role.instructions_path.read_text(encoding="utf-8")
    source = f"loops/{package.id}/{role.instructions_path.name}"
    return "".join(
        (
            MANAGED_HEADER,
            f"# Source: loops/{package.id}/manifest.toml + {source}\n",
            f"model = {json.dumps(role.model, ensure_ascii=False)}\n",
            "model_reasoning_effort = "
            f"{json.dumps(role.reasoning_effort, ensure_ascii=False)}\n",
            f"service_tier = {json.dumps(role.service_tier, ensure_ascii=False)}\n",
            "developer_instructions = "
            f"{json.dumps(instructions, ensure_ascii=False)}\n",
        )
    )


def install_loop_package(
    package: LoopPackage,
    *,
    codex_home: str | Path | None = None,
    managed_root: str | Path | None = None,
) -> tuple[InstalledProfile, ...]:
    home = resolve_codex_home(codex_home)
    managed = _managed_path(managed_root)
    installation = _installation_plan(package, home=home, managed_root=managed)
    rendered = {
        item.runtime_profile: render_profile_adapter(
            package, _role_by_id(package, item.role)
        )
        for item in installation
    }

    obsolete = _obsolete_installation(
        package, installation, home=home, managed_root=managed
    )
    _preflight_install(
        installation,
        rendered,
        obsolete=obsolete,
        home=home,
        managed_root=managed,
    )

    package_managed_root = managed / package.id
    package_managed_root.mkdir(parents=True, exist_ok=True)
    home.mkdir(parents=True, exist_ok=True)
    for item in installation:
        content = rendered[item.runtime_profile]
        if not item.adapter_path.exists() or item.adapter_path.read_text(
            encoding="utf-8"
        ) != content:
            _atomic_write(item.adapter_path, content)
    for item in installation:
        if not item.symlink_path.is_symlink():
            item.symlink_path.symlink_to(item.adapter_path)
    for adapter_path, symlink_path in obsolete:
        if symlink_path.is_symlink():
            symlink_path.unlink()
        adapter_path.unlink()
    return installation


def check_loop_installation(
    package: LoopPackage,
    *,
    codex_home: str | Path | None = None,
    managed_root: str | Path | None = None,
) -> tuple[InstalledProfile, ...]:
    home = resolve_codex_home(codex_home)
    managed = _managed_path(managed_root)
    installation = _installation_plan(package, home=home, managed_root=managed)
    obsolete = _obsolete_installation(
        package, installation, home=home, managed_root=managed
    )
    if obsolete:
        names = ", ".join(adapter.name for adapter, _ in obsolete)
        raise LoopPackageError(
            f"obsolete managed adapters remain for loop {package.id}: {names}"
        )
    for item in installation:
        expected = render_profile_adapter(package, _role_by_id(package, item.role))
        _check_generated_target(item.adapter_path, expected, require_present=True)
        _check_runtime_target(
            item.symlink_path, item.adapter_path, require_present=True
        )
    return installation


def _load_manifest(path: Path) -> LoopPackage:
    try:
        with path.open("rb") as stream:
            document = tomllib.load(stream)
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise LoopPackageError(f"cannot read loop manifest {path}: {error}") from error
    if document.get("schema_version") != MANIFEST_SCHEMA_VERSION:
        raise LoopPackageError(
            f"{path}: schema_version must be {MANIFEST_SCHEMA_VERSION}"
        )

    loop_id = _required_string(document, "id", path)
    if not _ID_PATTERN.fullmatch(loop_id) or path.parent.name != loop_id:
        raise LoopPackageError(
            f"{path}: id must be a valid ID matching its package directory"
        )
    manual = _markdown_path(
        path.parent, _required_string(document, "manual", path), "manual"
    )
    communication_role = _required_string(document, "communication_role", path)
    if not _ROLE_PATTERN.fullmatch(communication_role):
        raise LoopPackageError(
            f"{path}: invalid communication_role {communication_role!r}"
        )

    layout_table = _required_table(document, "tmux", path)

    raw_roles = document.get("roles")
    if not isinstance(raw_roles, list) or not raw_roles:
        raise LoopPackageError(f"{path}: roles must be a non-empty ordered array")
    roles: list[LoopRole] = []
    for index, raw_role in enumerate(raw_roles):
        if not isinstance(raw_role, Mapping):
            raise LoopPackageError(f"{path}: roles[{index}] must be a table")
        role_id = _required_string(raw_role, "id", path)
        if not _ROLE_PATTERN.fullmatch(role_id):
            raise LoopPackageError(f"{path}: invalid role ID {role_id!r}")
        runtime_profile = _required_string(raw_role, "runtime_profile", path)
        if not _PROFILE_PATTERN.fullmatch(runtime_profile):
            raise LoopPackageError(
                f"{path}: invalid runtime profile {runtime_profile!r}"
            )
        roles.append(
            LoopRole(
                id=role_id,
                instructions_path=_markdown_path(
                    path.parent,
                    _required_string(raw_role, "instructions", path),
                    f"role {role_id} instructions",
                ),
                runtime_profile=runtime_profile,
                model=_required_string(raw_role, "model", path),
                reasoning_effort=_required_string(
                    raw_role, "reasoning_effort", path
                ),
                service_tier=_required_string(raw_role, "service_tier", path),
            )
        )

    role_ids = [role.id for role in roles]
    runtime_profiles = [role.runtime_profile for role in roles]
    if len(role_ids) != len(set(role_ids)):
        raise LoopPackageError(f"{path}: role IDs must be unique")
    if len(runtime_profiles) != len(set(runtime_profiles)):
        raise LoopPackageError(f"{path}: runtime profiles must be unique")
    if communication_role not in role_ids:
        raise LoopPackageError(
            f"{path}: communication_role {communication_role!r} must reference "
            "exactly one ordered role"
        )
    layout = _parse_tmux_layout(layout_table, role_ids=role_ids, source=path)

    return LoopPackage(
        id=loop_id,
        root=path.parent.resolve(),
        manifest_path=path.resolve(),
        manual_path=manual,
        roles=tuple(roles),
        communication_role=communication_role,
        layout=layout,
    )


def _parse_tmux_layout(
    values: Mapping[str, Any], *, role_ids: list[str], source: Path
) -> TmuxLayout:
    layout_name = _required_string(values, "layout", source)
    if layout_name == "even-horizontal":
        if "steps" in values:
            raise LoopPackageError(
                f"{source}: even-horizontal tmux layout must not declare split steps"
            )
        columns = values.get("columns")
        equal_width = values.get("equal_width")
        if equal_width is not True:
            raise LoopPackageError(
                f"{source}: even-horizontal tmux layout requires equal_width=true"
            )
        if isinstance(columns, bool) or not isinstance(columns, int) or columns < 2:
            raise LoopPackageError(
                f"{source}: tmux columns must be an integer >= 2"
            )
        if columns != len(role_ids):
            raise LoopPackageError(
                f"{source}: tmux columns ({columns}) must equal role count "
                f"({len(role_ids)})"
            )
        return EvenHorizontalTmuxLayout(
            name=layout_name,
            columns=columns,
            equal_width=equal_width,
        )

    if layout_name != "split-plan":
        raise LoopPackageError(f"{source}: unsupported tmux layout {layout_name!r}")
    if "columns" in values or "equal_width" in values:
        raise LoopPackageError(
            f"{source}: split-plan tmux layout must not declare columns or equal_width"
        )
    raw_steps = values.get("steps")
    if not isinstance(raw_steps, list):
        raise LoopPackageError(
            f"{source}: split-plan tmux steps must be an ordered array"
        )
    expected_count = len(role_ids) - 1
    if len(raw_steps) != expected_count:
        raise LoopPackageError(
            f"{source}: split-plan tmux steps ({len(raw_steps)}) must cover "
            f"every non-root role ({expected_count})"
        )

    steps: list[TmuxSplitStep] = []
    for index, raw_step in enumerate(raw_steps):
        if not isinstance(raw_step, Mapping):
            raise LoopPackageError(f"{source}: tmux steps[{index}] must be a table")
        role = _required_string(raw_step, "role", source)
        expected_role = role_ids[index + 1]
        if role != expected_role:
            raise LoopPackageError(
                f"{source}: tmux steps[{index}] role {role!r} must create "
                f"ordered role {expected_role!r}"
            )
        target = _required_string(raw_step, "target", source)
        earlier_roles = role_ids[: index + 1]
        if target not in earlier_roles:
            raise LoopPackageError(
                f"{source}: tmux steps[{index}] target {target!r} must reference "
                "an earlier role"
            )
        direction = _required_string(raw_step, "direction", source)
        if direction not in {"horizontal", "vertical"}:
            raise LoopPackageError(
                f"{source}: tmux steps[{index}] direction must be horizontal or vertical"
            )
        percentage = raw_step.get("percentage")
        if (
            isinstance(percentage, bool)
            or not isinstance(percentage, int)
            or not 1 <= percentage <= 99
        ):
            raise LoopPackageError(
                f"{source}: tmux steps[{index}] percentage must be an integer "
                "from 1 through 99"
            )
        steps.append(
            TmuxSplitStep(
                role=role,
                target=target,
                direction=direction,
                percentage=percentage,
            )
        )
    return SplitPlanTmuxLayout(name=layout_name, steps=tuple(steps))


def _loops_root(value: str | Path | None) -> Path:
    root = Path(value).expanduser() if value is not None else default_loops_dir()
    try:
        resolved = root.resolve(strict=True)
    except OSError as error:
        raise LoopPackageError(f"loop package directory is not accessible: {root}") from error
    if not resolved.is_dir():
        raise LoopPackageError(f"loop package path is not a directory: {resolved}")
    return resolved


def _markdown_path(root: Path, value: str, label: str) -> Path:
    relative = Path(value)
    if relative.is_absolute() or ".." in relative.parts or relative.suffix != ".md":
        raise LoopPackageError(f"{label} must be a package-local Markdown path")
    try:
        resolved = (root / relative).resolve(strict=True)
        resolved.relative_to(root.resolve())
    except (OSError, ValueError) as error:
        raise LoopPackageError(
            f"{label} is not an accessible package-local Markdown file: {value}"
        ) from error
    if not resolved.is_file():
        raise LoopPackageError(f"{label} is not a file: {resolved}")
    return resolved


def _required_string(values: Mapping[str, Any], key: str, source: Path) -> str:
    value = values.get(key)
    if not isinstance(value, str) or not value:
        raise LoopPackageError(f"{source}: {key} must be a non-empty string")
    return value


def _required_table(
    values: Mapping[str, Any], key: str, source: Path
) -> Mapping[str, Any]:
    value = values.get(key)
    if not isinstance(value, Mapping):
        raise LoopPackageError(f"{source}: {key} must be a table")
    return value


def _managed_path(value: str | Path | None) -> Path:
    path = (
        Path(value).expanduser()
        if value is not None
        else default_managed_root()
    )
    return path.absolute()


def _installation_plan(
    package: LoopPackage, *, home: Path, managed_root: Path
) -> tuple[InstalledProfile, ...]:
    package_root = managed_root / package.id
    return tuple(
        InstalledProfile(
            role=role.id,
            runtime_profile=role.runtime_profile,
            adapter_path=package_root / f"{role.runtime_profile}.config.toml",
            symlink_path=home / f"{role.runtime_profile}.config.toml",
        )
        for role in package.roles
    )


def _preflight_install(
    installation: tuple[InstalledProfile, ...],
    rendered: Mapping[str, str],
    *,
    obsolete: tuple[tuple[Path, Path], ...],
    home: Path,
    managed_root: Path,
) -> None:
    _check_directory_target(home, "CODEX_HOME")
    _check_directory_target(managed_root.parent, "managed area parent")
    _check_directory_target(managed_root, "managed adapter root")
    if installation:
        _check_directory_target(
            installation[0].adapter_path.parent, "loop managed adapter directory"
        )
    for item in installation:
        _check_generated_target(
            item.adapter_path, rendered[item.runtime_profile], require_present=False
        )
        _check_runtime_target(
            item.symlink_path, item.adapter_path, require_present=False
        )
    for adapter_path, symlink_path in obsolete:
        _check_managed_obsolete_adapter(adapter_path)
        _check_runtime_target(symlink_path, adapter_path, require_present=False)


def _obsolete_installation(
    package: LoopPackage,
    installation: tuple[InstalledProfile, ...],
    *,
    home: Path,
    managed_root: Path,
) -> tuple[tuple[Path, Path], ...]:
    package_root = managed_root / package.id
    if not package_root.exists():
        return ()
    if package_root.is_symlink() or not package_root.is_dir():
        raise LoopPackageError(
            f"loop managed adapter directory is not an unmanaged-safe directory: "
            f"{package_root}"
        )
    expected = {item.adapter_path for item in installation}
    obsolete: list[tuple[Path, Path]] = []
    for adapter_path in sorted(package_root.iterdir(), key=lambda path: path.name):
        if adapter_path in expected:
            continue
        if adapter_path.suffixes[-2:] != [".config", ".toml"]:
            raise LoopPackageError(
                f"unexpected file in loop managed adapter directory: {adapter_path}"
            )
        obsolete.append((adapter_path, home / adapter_path.name))
    return tuple(obsolete)


def _check_managed_obsolete_adapter(path: Path) -> None:
    if path.is_symlink() or not path.is_file():
        raise LoopPackageError(f"obsolete adapter has conflicting type: {path}")
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as error:
        raise LoopPackageError(f"cannot read obsolete adapter {path}: {error}") from error
    if not content.startswith(MANAGED_HEADER):
        raise LoopPackageError(f"obsolete adapter is not managed by codex-crew: {path}")


def _check_directory_target(path: Path, label: str) -> None:
    if path.is_symlink() or (path.exists() and not path.is_dir()):
        raise LoopPackageError(f"{label} is not an unmanaged-safe directory: {path}")


def _check_generated_target(
    path: Path, expected: str, *, require_present: bool
) -> None:
    if path.is_symlink() or (path.exists() and not path.is_file()):
        raise LoopPackageError(f"generated adapter target has conflicting type: {path}")
    if not path.exists():
        if require_present:
            raise LoopPackageError(f"generated adapter is missing: {path}")
        return
    try:
        actual = path.read_text(encoding="utf-8")
    except OSError as error:
        raise LoopPackageError(f"cannot read generated adapter {path}: {error}") from error
    if not actual.startswith(MANAGED_HEADER):
        raise LoopPackageError(f"generated adapter is not managed by codex-crew: {path}")
    if require_present and actual != expected:
        raise LoopPackageError(f"generated adapter is stale: {path}")


def _check_runtime_target(
    path: Path, adapter: Path, *, require_present: bool
) -> None:
    if not path.is_symlink():
        if path.exists():
            raise LoopPackageError(f"runtime profile target is not a symlink: {path}")
        if require_present:
            raise LoopPackageError(f"runtime profile symlink is missing: {path}")
        return
    try:
        raw_target = Path(os.readlink(path))
    except OSError as error:
        raise LoopPackageError(f"cannot read runtime profile symlink {path}: {error}") from error
    target = raw_target if raw_target.is_absolute() else path.parent / raw_target
    if target.resolve(strict=False) != adapter.resolve(strict=False):
        raise LoopPackageError(
            f"runtime profile symlink points to the wrong target: {path} -> {raw_target}"
        )


def _atomic_write(path: Path, content: str) -> None:
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as stream:
            stream.write(content)
            temporary_name = stream.name
        os.replace(temporary_name, path)
    finally:
        if temporary_name is not None:
            try:
                Path(temporary_name).unlink()
            except FileNotFoundError:
                pass


def _role_by_id(package: LoopPackage, role_id: str) -> LoopRole:
    return next(role for role in package.roles if role.id == role_id)
